
import articleXMLReader.XMLParser;
import org.dom4j.DocumentException;

/**
 * test function.
 */
public class Test {

    public static void main(final String[] args) throws DocumentException {
        XMLParser xmlParser = new XMLParser();
        xmlParser.setXMLParser("<body>\n" +
                " \n" +
                "Dibujo1A\n" +
                " <segment features='correccion' state='active' comment='Esta es la historia de'> </segment><segment features='correccion' state='active' comment='000'>Es</segment> una familia tradicional. <segment features='correccion' state='active' comment='Los padres'> </segment><segment features='correccion' state='active' comment='tienen'>Tienen</segment> dos hijos<segment features='correccion' state='active' comment=','> </segment>Carlos y María,<segment features='correccion' state='active' comment='ellos'> </segment>son obedientes. <segment features='correccion' state='active' comment='La familia'> </segment><segment features='correccion' state='active' comment='también'>También</segment> tiene un perro <segment features='correccion' state='active' comment='000'>con ellos</segment>.\n" +
                "  Cuando Carlos y María <segment features='correccion' state='active' comment='se hicieron'>seran</segment> mayores,<segment features='correccion' state='active' comment='se'> </segment><segment features='correccion' state='active' comment='fueron'>iran</segment> a la universidad <segment features='correccion' state='active' comment='&quot;Álava&quot;'>¨Álaca¨</segment>en España.  <segment features='correccion' state='active' comment='Era'>Es</segment> una<segment features='correccion' state='active' comment='buena'> </segment><segment features='correccion' state='active' comment='oportunidad'>optunidad</segment> <segment features='correccion' state='active' comment='000'>bien</segment> para ellos.  Pero, sus padres se <segment features='correccion' state='active' comment='pusieron'>ponen</segment> tristes<segment features='correccion' state='active' comment='000'>.</segment>  <segment features='correccion' state='active' comment='porque'>Porque</segment> España <segment features='correccion' state='active' comment='está'>es</segment> muy <segment features='correccion' state='active' comment='lejos'>lejo</segment> de Taiwán y <segment features='correccion' state='active' comment='era'>es</segment><segment features='correccion' state='active' comment='la'> </segment>primera vez <segment features='correccion' state='active' comment='que'>para</segment> ellos <segment features='correccion' state='active' comment='salían'>salir</segment> de casa.\n" +
                "  <segment features='correccion' state='active' comment='000'>Hace</segment><segment features='correccion' state='active' comment='Después de'> </segment><segment features='correccion' state='active' comment='dos'>2</segment> años,<segment features='correccion' state='active' comment='los'> </segment><segment features='correccion' state='active' comment='padres'>Padres</segment> siempre <segment features='correccion' state='active' comment='recordaban'>recodaban</segment><segment features='correccion' state='active' comment='a'> </segment>sus hijos y el perro estaba solo.  <segment features='correccion' state='active' comment='000'>Es que</segment> <segment features='correccion' state='active' comment='Todo'>todos</segment> <segment features='correccion' state='active' comment='parecía'>son</segment> <segment features='correccion' state='active' comment='similar'>similares</segment> pero <segment features='correccion' state='active' comment='faltaba'>falta</segment> algo <segment features='correccion' state='active' comment='000'>cosa</segment><segment features='correccion' state='active' comment=','>.</segment>  <segment features='correccion' state='active' comment='000'>Por eso</segment> la vida <segment features='correccion' state='active' comment='se volvió'>será</segment> demasiado tranquila<segment features='correccion' state='active' comment=','>.</segment>  <segment features='correccion' state='active' comment='todos'>Todos</segment> <segment features='correccion' state='active' comment='estaban'>son</segment> nostálgicos.\n" +
                "  Después<segment features='correccion' state='active' comment='de un poco más de cinco años'> </segment><segment features='correccion' state='active' comment='000'>una semana</segment>, los padres <segment features='correccion' state='active' comment='están'>son</segment> sorprendidos<segment features='correccion' state='active' comment=','>.</segment>  <segment features='correccion' state='active' comment='000'>Porque</segment> sus hijos<segment features='correccion' state='active' comment='han'> </segment><segment features='correccion' state='active' comment='regresado'>regresan</segment> a casa y <segment features='correccion' state='active' comment='000'>ellos</segment> <segment features='correccion' state='active' comment='están'>son</segment><segment features='correccion' state='active' comment='muy'> </segment>cambiados.  La ropa de <segment features='correccion' state='active' comment='los'>sus</segment> hijos <segment features='correccion' state='active' comment='es'>son</segment> extravagante<segment features='correccion' state='active' comment=','> </segment>pero<segment features='correccion' state='active' comment='se ven muy'> </segment>guapos<segment features='correccion' state='active' comment=','> </segment><segment features='correccion' state='active' comment='además'>y</segment><segment features='correccion' state='active' comment=','> </segment>el pelo de María <segment features='correccion' state='active' comment='está'>es</segment> rizado.  Carlos tiene el pelo largo y<segment features='correccion' state='active' comment='un'> </segment>poco rizado.  ¡Qué bien!  Creo que<segment features='correccion' state='active' comment='ahora'> </segment><segment features='correccion' state='active' comment='tienen'>sea</segment> una vida feliz.\n" +
                "\n" +
                "Dibujo1B<segment features='correccion' state='active' comment='000'>\u000B</segment>  <segment features='correccion' state='active' comment='Están'>Hay</segment> dos personas en <segment features='correccion' state='active' comment='una'>el</segment> <segment features='correccion' state='active' comment='sala,'>dibujo.</segment>  <segment features='correccion' state='active' comment='están'>Estan</segment> <segment features='correccion' state='active' comment='sentados'>sentando</segment> en <segment features='correccion' state='active' comment='un'>una</segment> sillón.  <segment features='correccion' state='active' comment='000'>Sobre</segment> <segment features='correccion' state='active' comment='El'>el</segment> hombre<segment features='correccion' state='active' comment='000'>,</segment> se llama Javier, tiene el pelo rizado y es tímido.  <segment features='correccion' state='active' comment='000'>Sobre</segment> <segment features='correccion' state='active' comment='La'>la</segment> mujer<segment features='correccion' state='active' comment='000'>,</segment> se llama Estela, tiene el pelo rizado y nariz respingona.  <segment features='correccion' state='active' comment='Sobre'>Abajo</segment> <segment features='correccion' state='active' comment='000'>de</segment> ellos <segment features='correccion' state='active' comment='vuela'>hay</segment> un <segment features='correccion' state='active' comment='ángel'>dio</segment>, <segment features='correccion' state='active' comment='000'>se llama</segment><segment features='correccion' state='active' comment='el'> </segment><segment features='correccion' state='active' comment='ángel'>dío</segment><segment features='correccion' state='active' comment='del'> </segment>amor, Cupido<segment features='correccion' state='active' comment=','>.</segment> <segment features='correccion' state='active' comment='quien'> </segment><segment features='correccion' state='active' comment='es'>Es</segment> travieso<segment features='correccion' state='active' comment=','> </segment><segment features='correccion' state='active' comment='000'>y</segment> indeciso<segment features='correccion' state='active' comment='y'> </segment><segment features='correccion' state='active' comment='quiere'>que</segment> unir a Javier y<segment features='correccion' state='active' comment='a'> </segment>Estela.  Javier<segment features='correccion' state='active' comment='000'>,</segment> <segment features='correccion' state='active' comment='está'>se pone</segment> nervioso, pero Estela <segment features='correccion' state='active' comment='000'>piensa</segment><segment features='correccion' state='active' comment='está'> </segment><segment features='correccion' state='active' comment='interesada'>intersada</segment><segment features='correccion' state='active' comment='000'>.</segment><segment features='correccion' state='active' comment='en Javier.'> </segment> ¡Ja ja!\n" +
                "  Cuando Javier mira su programa <segment features='correccion' state='active' comment='favorito'>favoito</segment><segment features='correccion' state='active' comment=','>.</segment> <segment features='correccion' state='active' comment='el cual'> </segment><segment features='correccion' state='active' comment='es'>Es</segment> <segment features='correccion' state='active' comment='000'>una programa</segment> entretenido.  Cupido lanza <segment features='correccion' state='active' comment='una'>la</segment> flecha a Javier y<segment features='correccion' state='active' comment='a'> </segment>Estela<segment features='correccion' state='active' comment=','>.</segment>  <segment features='correccion' state='active' comment='pero'>Pero</segment> al final <segment features='correccion' state='active' comment='000'>se</segment> <segment features='correccion' state='active' comment='falla'>falta</segment><segment features='correccion' state='active' comment=','>.</segment> <segment features='correccion' state='active' comment='se la'> </segment><segment features='correccion' state='active' comment='lanzó'>Lanza</segment> a la televisión.  ¡Qué pena!  Estela <segment features='correccion' state='active' comment='estaba'>es</segment> ilusionada <segment features='correccion' state='active' comment='000'>que ocurrío terminado</segment>.\n" +
                "  ¡Qué increíble!  El resultado es muy sorprendente<segment features='correccion' state='active' comment=','>.</segment>  Javier<segment features='correccion' state='active' comment='está'> </segment>enamorado <segment features='correccion' state='active' comment='de'>con</segment> <segment features='correccion' state='active' comment='una'>un</segment> televisión y Estela <segment features='correccion' state='active' comment='está'>es</segment> disgustada.  Es un cuento muy interesante<segment features='correccion' state='active' comment=','> </segment>¿<segment features='correccion' state='active' comment='no'>sí</segment>?  <segment features='correccion' state='active' comment='Javier'>La persona</segment><segment features='correccion' state='active' comment='está'> </segment>enamorado <segment features='correccion' state='active' comment='de'>con</segment> un <segment features='correccion' state='active' comment='objeto'>objecto</segment>.\n" +
                "\n" +
                "\n" +
                "    </body>");
        System.out.println(xmlParser.getOriginalArticle());
        System.out.println(xmlParser.getCorrectedArticle());
    }
}
