
import articleXMLReader.XMLParser;
import org.dom4j.DocumentException;

/**
 * test function.
 */
public class Test {

    public static void main(final String[] args) throws DocumentException {
        XMLParser xmlParser = new XMLParser();
        xmlParser.setXMLParser("<body>\n" +
                "\n" +
                "   Hola! Me llamo XXX<segment features='correction' state='active' comment='XXX.'> XXX.</segment> Mi <segment features='correction' state='active' comment='fecha de nacimiento'>cumplcaños</segment> <segment features='correction' state='active' comment='es el'>es</segment> XXX de XXX de <segment features='correction' state='active' comment='XXX'>XXX</segment>. Por eso <segment features='correction' state='active' comment='soy de'>soy</segment> <segment features='correction' state='active' comment='Libra.'>libra.</segment> Soy de <segment features='correction' state='active' comment='Taiwán.'>Taiwan.</segment> <segment features='correction' state='active' comment='Tengo'>Tego</segment> <segment features='correction' state='active' comment='una'>un</segment> <segment features='correction' state='active' comment='familia feliz.'>venturoso</segment> <segment features='correction' state='active' comment='000'>familia.</segment> Mi familia <segment features='correction' state='active' comment='está integrada por:'>tener</segment> <segment features='correction' state='active' comment='papá,'>padre,</segment> <segment features='correction' state='active' comment='mamá,'>mader,</segment> abuelo y <segment features='correction' state='active' comment='mi'>un</segment> hermana. Vivimos en <segment features='correction' state='active' comment='XXX'>XXX</segment>. Hablo chino, taiwanés, un poco de inglés y español. Estudio en la <segment features='correction' state='active' comment='Universidad'>universidad</segment> <segment features='correction' state='active' comment='XXX'>XXX</segment>. Soy <segment features='correction' state='active' comment='licenciado'>licenciadola</segment> en artes plásticas <segment features='correction' state='active' comment='y escultura'>escultura</segment> de <segment features='correction' state='active' comment='piedra.'>piedra</segment> <segment features='correction' state='active' comment='000'>grupo.</segment> \n" +
                "  <segment features='correction' state='active' comment='Mido un metro setenta y ocho.'>Mi altura</segment> <segment features='correction' state='active' comment='000'>cien setenta y ocho agua.</segment> Peso sesenta y nueve <segment features='correction' state='active' comment='kilos.'>lcilo.</segment> Me gusta comer tortilla de <segment features='correction' state='active' comment='patatas,'>ptatas,</segment> paella, queso, salmón, chuleta, tostada, manzana, naranja y chocolate. Me gusta jugar al <segment features='correction' state='active' comment='béisbol,'>baseball,</segment> <segment features='correction' state='active' comment='al baloncesto,'>baloucesto,</segment> <segment features='correction' state='active' comment='a los videojuegos y al'>ordernador,</segment> <segment features='correction' state='active' comment='fútbol. También me gusta jugar a los'>fútbol, centimetro.</segment> <segment features='correction' state='active' comment='videojuegos'>Vido game</segment> y <segment features='correction' state='active' comment='pintar.'>pintura.</segment> Desde <segment features='correction' state='active' comment='pequeño'>pegueño</segment> me <segment features='correction' state='active' comment='gustaba'>gusta</segment> <segment features='correction' state='active' comment='pintar'>pintura</segment> <segment features='correction' state='active' comment='000'>y</segment> <segment features='correction' state='active' comment='cuadros y'>cuadro</segment> dibujos. Por <segment features='correction' state='active' comment='eso asisto a'>eso</segment> <segment features='correction' state='active' comment='la'>estudio</segment> clase de bellas <segment features='correction' state='active' comment='artes.'>artes</segment> <segment features='correction' state='active' comment='Estos estudios'>esta enseñanza</segment> <segment features='correction' state='active' comment='se imparten en secundaria'>secundaná</segment> <segment features='correction' state='active' comment='y en'>y</segment> bachillerato. \n" +
                "  Me gusta Europa <segment features='correction' state='active' comment='y'>soy</segment> <segment features='correction' state='active' comment='estaré en'>está</segment> Europa <segment features='correction' state='active' comment='desde'>de</segment> <segment features='correction' state='active' comment='el veintitrés'>véintitres</segment> de junio <segment features='correction' state='active' comment='hasta'>a</segment> <segment features='correction' state='active' comment='el primero'>uno</segment> de julio. <segment features='correction' state='active' comment='Será una experiencia maravillosa.'>那將會是一個很棒的 experenica.</segment>\n" +
                "\n" +
                "    </body>");
        System.out.println(xmlParser.getOriginalArticle());
        System.out.println(xmlParser.getCorrectedArticle());
    }
}
