package controllers;

import articleXMLReader.XMLParser;

public class Main {

    /**
     * This is a test.
     */
    public static void main(final String[] args) {
        String xml = "<body>\n" +
                "11001 PU 沈敬豪 is dog\n" +
                "\n" +
                "Érase una vezz<segment features=\"correccion\" state=\"active\" comment=\"000\">,</segment> una niña<segment features=\"correccion\" state=\"active\" comment=\"a la que llamaban Caperucita Roja porque siempre\"> </segment>llevaba una caperuza roja<segment features=\"correccion\" state=\"active\" comment=\", ella\"> </segment>vivía en un bosque<segment features=\"correccion\" state=\"active\" comment=\", por el cual\">.</segment> <segment features=\"correccion\" state=\"active\" comment=\"000\">Siempre</segment> andaba todos los días. Un día, su madre le dijo que su abuela estaba enferma<segment features=\"correccion\" state=\"active\" comment=\",\">.</segment> <segment features=\"correccion\" state=\"active\" comment=\"así\">Así</segment> que<segment features=\"correccion\" state=\"active\" comment=\"le pidió\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"000\">ella</segment><segment features=\"correccion\" state=\"active\" comment=\"que la\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"visitara\">visitó</segment> <segment features=\"correccion\" state=\"active\" comment=\"000\">a su abuela</segment>. <segment features=\"correccion\" state=\"active\" comment=\"Antes\">Andes</segment> de salir <segment features=\"correccion\" state=\"active\" comment=\"de\">la</segment> casa, su madre le aconsejó que<segment features=\"correccion\" state=\"active\" comment=\"se mantuviera lejos\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"000\">las cosa</segment><segment features=\"correccion\" state=\"active\" comment=\"del\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"peligro\">peligrosa</segment> <segment features=\"correccion\" state=\"active\" comment=\"000\">fuera</segment>. <segment features=\"correccion\" state=\"active\" comment=\"000\">Y</segment> <segment features=\"correccion\" state=\"active\" comment=\"Caperucita\">ella</segment> salió <segment features=\"correccion\" state=\"active\" comment=\"de\">a</segment> casa <segment features=\"correccion\" state=\"active\" comment=\"a\">de</segment> <segment features=\"correccion\" state=\"active\" comment=\"las\">la</segment> <segment features=\"correccion\" state=\"active\" comment=\"tres de la tarde\">hora 3:00 PM</segment>.\n" +
                "Mientras andaba en el bosque, <segment features=\"correccion\" state=\"active\" comment=\"000\">como</segment> preocupada <segment features=\"correccion\" state=\"active\" comment=\"por\">a</segment> su abuela, <segment features=\"correccion\" state=\"active\" comment=\"000\">ella</segment><segment features=\"correccion\" state=\"active\" comment=\"se\"> </segment>olvidó <segment features=\"correccion\" state=\"active\" comment=\"000\">algo</segment><segment features=\"correccion\" state=\"active\" comment=\"de\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"peligros\">peligroso</segment><segment features=\"correccion\" state=\"active\" comment=\", pues en\">.</segment> <segment features=\"correccion\" state=\"active\" comment=\"el\">Del</segment> camino<segment features=\"correccion\" state=\"active\" comment=\"000\">,</segment> había flores y mariposas. <segment features=\"correccion\" state=\"active\" comment=\"Cuando\">Mientras</segment><segment features=\"correccion\" state=\"active\" comment=\"000\">,</segment> ella cantaba y cogía flores para su abuela<segment features=\"correccion\" state=\"active\" comment=\"000\">. De repente,</segment> <segment features=\"correccion\" state=\"active\" comment=\"apareció\">aparecía</segment> un lobo y le preguntó qué <segment features=\"correccion\" state=\"active\" comment=\"hacía\">hizo</segment> <segment features=\"correccion\" state=\"active\" comment=\"000\">la niña</segment>.\n" +
                "<segment features=\"correccion\" state=\"active\" comment=\"000\">Despúes,</segment> <segment features=\"correccion\" state=\"active\" comment=\"El\">la</segment> lobo<segment features=\"correccion\" state=\"active\" comment=\"se apresuró y\"> </segment>llegó<segment features=\"correccion\" state=\"active\" comment=\"antes\"> </segment>a la casa de la abuela. La <segment features=\"correccion\" state=\"active\" comment=\"anciana\">abuela</segment> estaba débil y no podía levantarse. El lobo<segment features=\"correccion\" state=\"active\" comment=\"se\"> </segment>comió<segment features=\"correccion\" state=\"active\" comment=\"a\"> </segment>la abuela<segment features=\"correccion\" state=\"active\" comment=\",\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"000\">y</segment> <segment features=\"correccion\" state=\"active\" comment=\"000\">despúes imitó a la abuela.</segment> <segment features=\"correccion\" state=\"active\" comment=\"se\">Se</segment> <segment features=\"correccion\" state=\"active\" comment=\"puso\">ponía</segment> <segment features=\"correccion\" state=\"active\" comment=\"su\">la</segment> ropa <segment features=\"correccion\" state=\"active\" comment=\"000\">de ella</segment> y se colocó <segment features=\"correccion\" state=\"active\" comment=\"su\">el</segment> gorro <segment features=\"correccion\" state=\"active\" comment=\"000\">de ella</segment>.\n" +
                "Cuando Caperucita llegó a la casa de su abuela, tocó<segment features=\"correccion\" state=\"active\" comment=\"a\"> </segment>la puerta. El lobo se <segment features=\"correccion\" state=\"active\" comment=\"cubrió\">cubró</segment><segment features=\"correccion\" state=\"active\" comment=\"con\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"las\">la</segment> mantas en la cama <segment features=\"correccion\" state=\"active\" comment=\"e\">y</segment> imitó la voz de la abuela. <segment features=\"correccion\" state=\"active\" comment=\"000\">Luego,</segment> Caperucita entró<segment features=\"correccion\" state=\"active\" comment=\"a\"> </segment>la casa y<segment features=\"correccion\" state=\"active\" comment=\"le\"> </segment>preguntó a su abuela<segment features=\"correccion\" state=\"active\" comment=\":\">.</segment><segment features=\"correccion\" state=\"active\" comment=\"—\"> </segment>¿<segment features=\"correccion\" state=\"active\" comment=\"Por qué\">Porque</segment> <segment features=\"correccion\" state=\"active\" comment=\"sus\">su</segment> ojos y orejas<segment features=\"correccion\" state=\"active\" comment=\"son\"> </segment>tan grandes?<segment features=\"correccion\" state=\"active\" comment=\",\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"000\">Y</segment><segment features=\"correccion\" state=\"active\" comment=\"te\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"pareces\">parecía</segment> un lobo.<segment features=\"correccion\" state=\"active\" comment=\"—\"> </segment>El lobo salió<segment features=\"correccion\" state=\"active\" comment=\"de\"> </segment>la cama y<segment features=\"correccion\" state=\"active\" comment=\"se\"> </segment>comió de un solo bocado a Caperucita.\n" +
                "<segment features=\"correccion\" state=\"active\" comment=\"Después de comer, el\">El</segment> lobo estaba cansado y tomó una siesta. Unos horas despúes, un cazador pasó y escuchó unos ronquidos muy fuertes<segment features=\"correccion\" state=\"active\" comment=\"se asomó y\">,</segment> <segment features=\"correccion\" state=\"active\" comment=\"vió\">veía</segment> <segment features=\"correccion\" state=\"active\" comment=\"al\">el</segment> lobo en la cama. <segment features=\"correccion\" state=\"active\" comment=\"000\">Cúando el lobo estaba dormido,</segment> <segment features=\"correccion\" state=\"active\" comment=\"El\">el</segment> <segment features=\"correccion\" state=\"active\" comment=\"cazador\">cazado</segment> entró<segment features=\"correccion\" state=\"active\" comment=\",\"> </segment><segment features=\"correccion\" state=\"active\" comment=\"000\">y</segment> mató <segment features=\"correccion\" state=\"active\" comment=\"al\">el</segment> lobo<segment features=\"correccion\" state=\"active\" comment=\"000\">.</segment> <segment features=\"correccion\" state=\"active\" comment=\"y\">Y</segment> rescató<segment features=\"correccion\" state=\"active\" comment=\"a\"> </segment>Caperucita y<segment features=\"correccion\" state=\"active\" comment=\"a\"> </segment>su abuela. Ellas<segment features=\"correccion\" state=\"active\" comment=\"estaban\"> </segment>muy <segment features=\"correccion\" state=\"active\" comment=\"agradecidas\">graciosas</segment> y la abuelita invitó <segment features=\"correccion\" state=\"active\" comment=\"al\">el</segment> cazador a <segment features=\"correccion\" state=\"active\" comment=\"000\">su casa</segment> <segment features=\"correccion\" state=\"active\" comment=\"comer\">tomar</segment> pan dulce y <segment features=\"correccion\" state=\"active\" comment=\"beber\">comer</segment> chocolate caliente.\n" +
                "<segment features=\"correccion\" state=\"active\" comment=\"Más\">Por la</segment> tarde, el cazador acompañó a Caperucita a su casa. <segment features=\"correccion\" state=\"active\" comment=\"000\">Y</segment><segment features=\"correccion\" state=\"active\" comment=\"Ese día,\"> </segment>Caperucita aprendió una <segment features=\"correccion\" state=\"active\" comment=\"000\">una</segment> importante lección<segment features=\"correccion\" state=\"active\" comment=\":\">.</segment> <segment features=\"correccion\" state=\"active\" comment=\"–\">“</segment>No <segment features=\"correccion\" state=\"active\" comment=\"hablar\">digas la camino de la familia casa</segment> <segment features=\"correccion\" state=\"active\" comment=\"con\">a los</segment> desconocidos.<segment features=\"correccion\" state=\"active\" comment=\"–\">”</segment>\n" +
                "    </body>";
        System.out.println(xml + "\n");
        XMLParser xmlParser = new XMLParser();
        try {
            xmlParser.setXMLParser(xml);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println(xmlParser.getOriginalArticle().toString() + "\n");
        System.out.println(xmlParser.getCorrectedArticle().toString() + "\n");
    }
}
